table 'All Data'
	lineageTag: 1dfe5f9c-6495-407b-a1ba-f85481d9eefb

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 7471b6ab-88d7-4970-aa0c-35e2663c31ec
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: d0869ae0-d754-47e2-b26b-19c538326a17
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Category.1'
		dataType: string
		lineageTag: 4497c6c0-6d99-4a2d-bf3b-e676286a9a48
		summarizeBy: none
		sourceColumn: Category.1

		annotation SummarizationSetBy = Automatic

	column job_type
		dataType: string
		lineageTag: 734a19cd-6270-4c87-95b4-3feefff50e5f
		summarizeBy: none
		sourceColumn: job_type

		annotation SummarizationSetBy = Automatic

	column Posted
		dataType: dateTime
		formatString: Long Date
		lineageTag: d7e0ba86-38c2-4d17-9259-5ea6905aeb6d
		summarizeBy: none
		sourceColumn: Posted

		variation Variation
			isDefault
			relationship: 2847e164-3ba4-489d-bcf8-4b34d636fb30
			defaultHierarchy: LocalDateTable_b6bef76d-b067-4db2-a815-725007c62b4a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Budget
		dataType: double
		lineageTag: 809efd40-7df0-4ce1-ad88-39f567a08810
		summarizeBy: sum
		sourceColumn: Budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'est. budget'
		dataType: double
		lineageTag: 7df1078d-6a22-4688-8605-509cd4c96bca
		summarizeBy: sum
		sourceColumn: est. budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column hours/week
		dataType: string
		lineageTag: 0869beb1-3bae-4cde-ae7c-788ae941a307
		summarizeBy: none
		sourceColumn: hours/week

		annotation SummarizationSetBy = Automatic

	column duration
		dataType: string
		lineageTag: d69d97e0-189e-46c8-9cba-c80df2673395
		summarizeBy: none
		sourceColumn: duration

		annotation SummarizationSetBy = Automatic

	column UpWork
		dataType: string
		lineageTag: 37d8344c-7308-4191-9099-2103dfa19e39
		summarizeBy: none
		sourceColumn: UpWork

		annotation SummarizationSetBy = Automatic

	partition 'All Data' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\Apps\GItHubRebo\Web_Scraping-\All data\All Data Combined.csv"),[Delimiter=",", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID", Int64.Type}, {"Category", type text}, {"Category.1", type text}, {"job_type", type text}, {"Posted", type date}, {"Budget", type number}, {"est. budget", type number}, {"hours/week", type text}, {"duration", type text}, {"UpWork", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

