table AllData_Skills
	lineageTag: c31da968-ba77-4f31-98c2-a1821de47296

	column ID
		dataType: int64
		formatString: 0
		lineageTag: fdaea467-c1c6-44c0-b0fb-face5a09e0f8
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Tags
		dataType: string
		lineageTag: 7efb181b-8615-4f0a-8f26-de4d8b5343b0
		summarizeBy: none
		sourceColumn: Tags

		annotation SummarizationSetBy = Automatic

	column UpWork
		dataType: string
		lineageTag: 89fa8194-b727-426d-9050-5494ed6a7596
		summarizeBy: none
		sourceColumn: UpWork

		annotation SummarizationSetBy = Automatic

	partition AllData_Skills = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\Apps\GItHubRebo\Web_Scraping-\All data\AllData_expanded.csv"),[Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID", Int64.Type}, {"Tags", type text}, {"UpWork", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

