table Freelance_Yard
	lineageTag: ee207195-6c3f-4814-a5f8-fe972b49312b

	column Title
		dataType: string
		lineageTag: f5b125f2-7914-4250-accc-eb58e741f5b1
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column Link
		dataType: string
		lineageTag: 4cfa75d3-083e-48e2-82fc-18c3f3217847
		summarizeBy: none
		sourceColumn: Link

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 9e10a70a-9c62-4f80-a8c0-f38c061bc276
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column Budget
		dataType: double
		lineageTag: 168e3edd-8aac-4f43-9cc2-380e20e1edc7
		summarizeBy: sum
		sourceColumn: Budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Date Posted'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3720ce37-4a18-4613-b0e4-958023d8420b
		summarizeBy: none
		sourceColumn: Date Posted

		variation Variation
			isDefault
			relationship: 26f66443-8dec-4f30-92c4-bfcad7a1f9f0
			defaultHierarchy: LocalDateTable_a37f4102-01d8-4aa6-b141-64d2620f833a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'client name'
		dataType: string
		lineageTag: 6a623e79-c718-418e-afd7-27b8f77fcd04
		summarizeBy: none
		sourceColumn: client name

		annotation SummarizationSetBy = Automatic

	column 'Category.1'
		dataType: string
		lineageTag: 1a16cf41-c145-4dac-86b3-d0326009d968
		summarizeBy: none
		sourceColumn: Category.1

		annotation SummarizationSetBy = Automatic

	column Column1
		dataType: string
		lineageTag: edc1b42d-ae70-4fd5-b3ab-8539fe307516
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	partition Freelance_Yard = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\Apps\GItHubRebo\Web_Scraping-\Data\FreelanceYard.csv"),[Delimiter=",", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Renamed Columns" = Table.RenameColumns(#"Promoted Headers",{{"Client", "client name"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Budget", type number}, {"Date Posted", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

