table Freelancer
	lineageTag: f9111af4-c020-4d3d-b3ec-146d3b638aad

	measure 'Top skill' = ```
			
			VAR SummaryTable =
			    ADDCOLUMNS (
			        SUMMARIZE ( 'Freelancer_Skills', 'Freelancer_Skills'[Skills] ),
			        "TopSkill", CALCULATE ( count ( 'Freelancer_Skills'[Skills] ) )
			    )
			VAR TopProduct =
			    TOPN ( 1, SummaryTable, [TopSkill] , DESC )
			RETURN
			    CONCATENATEX (
			        TopProduct,
			        'Freelancer_Skills'[Skills] & " " & FORMAT ([TopSkill], "#,##0" ),","
			        
			    )
			
			
			
			```
		lineageTag: 15d52444-965d-4b44-b911-07d63a2f9e24

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 5a14b66b-2aa9-485e-b32d-c1582731dad2
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: string
		lineageTag: f4d620d8-f04e-41db-8b59-81d87eb32bda
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column Bids
		dataType: int64
		formatString: 0
		lineageTag: cb95dc01-378c-4c3d-87dc-007d4b18a801
		summarizeBy: none
		sourceColumn: Bids

		annotation SummarizationSetBy = Automatic

	column Price
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 24d87b72-3bad-42c4-9fc0-6fb5acb10ea2
		summarizeBy: sum
		sourceColumn: Price

		changedProperty = DataType

		annotation SummarizationSetBy = User

	column Type
		dataType: string
		lineageTag: 5c9611ab-3d3d-44ff-8822-5b17d8ed990d
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column Link
		dataType: string
		lineageTag: 48b719e6-3697-4472-bd66-5e6e8f706608
		summarizeBy: none
		sourceColumn: Link

		annotation SummarizationSetBy = Automatic

	column 'Days Left to bid'
		dataType: int64
		formatString: 0
		lineageTag: 8b2de0e3-cd96-49e7-a990-502276c4fc02
		summarizeBy: none
		sourceColumn: Days Left to bid

		annotation SummarizationSetBy = Automatic

	column 'Category.1'
		dataType: string
		lineageTag: 5a4b61dc-be6c-4368-898c-c11280b05548
		summarizeBy: none
		sourceColumn: Category.1

		annotation SummarizationSetBy = Automatic

	partition Freelancer = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\Apps\GItHubRebo\Web_Scraping-\Data\Freelancer.csv"),[Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID", Int64.Type}, {"Bids", Int64.Type}, {"Days Left to bid", Int64.Type}, {"Price", type number}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{""}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns",{{"Price", type number}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

