table Mostaql
	lineageTag: 7e713b1b-9f09-4647-adeb-74e97d601186

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 507f7e0d-4a88-40d3-8f0c-1ae2b6d9dfa0
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: string
		lineageTag: 32074696-cade-4a3a-a159-3bf107d71cc2
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column Category_English
		dataType: string
		lineageTag: d76a660c-6846-4768-8e7d-87063020e3cf
		summarizeBy: none
		sourceColumn: Category_English

		annotation SummarizationSetBy = Automatic

	column category_arabic
		dataType: string
		lineageTag: b6ce289d-c44a-4373-bcc8-41090795b0b2
		summarizeBy: none
		sourceColumn: category_arabic

		annotation SummarizationSetBy = Automatic

	column Posted
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9c80ea7e-7544-496b-9f6f-764a4ae14373
		summarizeBy: none
		sourceColumn: Posted

		variation Variation
			isDefault
			relationship: 67088b2a-8e64-44ab-92b3-1ea34a84ba8a
			defaultHierarchy: LocalDateTable_7f46b7f4-1943-4377-8086-f60de42d36bc.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Avg offer'
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: b24ae3de-74c9-41e9-8355-fdf5c4b289c9
		summarizeBy: sum
		sourceColumn: Avg offer

		annotation SummarizationSetBy = User

	column Duration(Days)
		dataType: int64
		formatString: 0
		lineageTag: 1c358264-4fe9-47b7-bd00-f848a439b247
		summarizeBy: sum
		sourceColumn: Duration(Days)

		annotation SummarizationSetBy = Automatic

	column 'Number of Offers'
		dataType: int64
		formatString: 0
		lineageTag: 543b2455-142f-4499-b0b7-578c3eba1b30
		summarizeBy: sum
		sourceColumn: Number of Offers

		annotation SummarizationSetBy = Automatic

	column Tags
		dataType: string
		lineageTag: 58859c30-0e0f-495f-8034-b1326e281a25
		summarizeBy: none
		sourceColumn: Tags

		annotation SummarizationSetBy = Automatic

	column Tags_en
		dataType: string
		lineageTag: cf38755c-07dc-4c3f-9008-545a4b41e331
		summarizeBy: none
		sourceColumn: Tags_en

		annotation SummarizationSetBy = Automatic

	column Link
		dataType: string
		lineageTag: 993d1251-7f60-463c-b20a-e20f720c6803
		summarizeBy: none
		sourceColumn: Link

		annotation SummarizationSetBy = Automatic

	partition Mostaql = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\Apps\GItHubRebo\Web_Scraping-\Mostaqel\job_listings_cleaned.csv"),[Delimiter=",", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID", Int64.Type}, {"Title", type text}, {"Category_English", type text}, {"category_arabic", type text}, {"Posted", type date}, {"Avg offer", type number}, {"Duration(Days)", Int64.Type}, {"Number of Offers", Int64.Type}, {"Tags", type text}, {"Tags_en", type text}, {"Link", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

