table Mostaql_Skills
	lineageTag: 0185cfd3-517a-4361-b408-4b1d3cf9eb42

	column ID
		dataType: string
		lineageTag: abd2d142-e544-4a34-b2a4-f7519116d2e0
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Tags
		dataType: string
		lineageTag: 123057fe-c76d-4366-bb4d-83dae152f1a7
		summarizeBy: none
		sourceColumn: Tags

		annotation SummarizationSetBy = Automatic

	column index
		dataType: string
		lineageTag: d904829b-3333-4f67-97fe-dca5bdbe35d1
		summarizeBy: none
		sourceColumn: index

		annotation SummarizationSetBy = Automatic

	partition Mostaql_Skills = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\Apps\GItHubRebo\Web_Scraping-\Data\MostaqelSkills.csv"),[Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
				in
				    #"Promoted Headers"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

