table Mostaql_Skills
	lineageTag: e6aa5320-1464-47fe-b4f4-1ea224aae492

	column ID
		dataType: int64
		formatString: 0
		lineageTag: f6b22e57-e968-4c09-9312-124ead91bd65
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column ID_skills_jobs
		dataType: int64
		formatString: 0
		lineageTag: 2cd5cc38-014b-4102-a619-f2459015b0dd
		summarizeBy: sum
		sourceColumn: ID_skills_jobs

		annotation SummarizationSetBy = Automatic

	column Tags_en
		dataType: string
		lineageTag: d770d69f-45c8-43f4-9dbe-8215119a4011
		summarizeBy: none
		sourceColumn: Tags_en

		annotation SummarizationSetBy = Automatic

	partition Mostaql_Skills = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\Apps\GItHubRebo\Web_Scraping-\Mostaqel\jobs_expanded.csv"),[Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID", Int64.Type}, {"ID_skills_jobs", Int64.Type}, {"Tags_en", type text}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

