table Mostaql_Skills
	lineageTag: 0185cfd3-517a-4361-b408-4b1d3cf9eb42

	column ID
		dataType: int64
		formatString: 0
		lineageTag: abd2d142-e544-4a34-b2a4-f7519116d2e0
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Tags_en
		dataType: string
		lineageTag: df11840b-692a-462b-9f0d-f0b60c0d4844
		summarizeBy: none
		sourceColumn: Tags_en

		annotation SummarizationSetBy = Automatic

	column ID_skills_jobs
		dataType: int64
		formatString: 0
		lineageTag: 39cc1b65-40a3-41ef-9438-3000d8ed9aaa
		summarizeBy: sum
		sourceColumn: ID_skills_jobs

		annotation SummarizationSetBy = Automatic

	partition Mostaql_Skills = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\Apps\GItHubRebo\Web_Scraping-\Mostaqel\jobs_expanded.csv"),[Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID", Int64.Type}, {"ID_skills_jobs", Int64.Type}, {"Tags_en", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

