table Mostaql_Skills
	lineageTag: 0185cfd3-517a-4361-b408-4b1d3cf9eb42

	column ID
		dataType: int64
		formatString: 0
		lineageTag: abd2d142-e544-4a34-b2a4-f7519116d2e0
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Tags_en
		dataType: string
		lineageTag: 123057fe-c76d-4366-bb4d-83dae152f1a7
		summarizeBy: none
		sourceColumn: Tags_en

		annotation SummarizationSetBy = Automatic

	column index
		dataType: int64
		formatString: 0
		lineageTag: f984255d-96af-4c6b-aae3-b0f9eb762f25
		summarizeBy: sum
		sourceColumn: index

		annotation SummarizationSetBy = Automatic

	partition Mostaql_Skills = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\Apps\GItHubRebo\Web_Scraping-\Data\MostaqelSkills.csv"),[Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"", Int64.Type}, {"ID", Int64.Type}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Changed Type",{"", "ID", "Tags"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Tags", "Tags_en"}, {"", "index"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

