table Mostaql
	lineageTag: 7e713b1b-9f09-4647-adeb-74e97d601186

	measure 'Most skill' = ```
			
			VAR SummaryTable =
			    ADDCOLUMNS (
			        SUMMARIZE ( 'Mostaql_Skills', 'Mostaql_Skills'[Tags_en] ),
			        "TopSkill", CALCULATE ( count ( 'Mostaql_Skills'[Tags_en] ) )
			    )
			VAR TopProduct =
			    TOPN ( 1, SummaryTable, [TopSkill] , DESC )
			RETURN
			    CONCATENATEX (
			        TopProduct,
			        'Mostaql_Skills'[Tags_en] & ": " & FORMAT ([TopSkill], "#,##0" ),","
			        
			    )
			
			
			
			```
		lineageTag: 472ce1ac-afdb-4580-bde8-7f22ed36b202

	column Title
		dataType: string
		lineageTag: 32074696-cade-4a3a-a159-3bf107d71cc2
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column Category_English
		dataType: string
		lineageTag: d76a660c-6846-4768-8e7d-87063020e3cf
		summarizeBy: none
		sourceColumn: Category_English

		annotation SummarizationSetBy = Automatic

	column Posted
		dataType: string
		lineageTag: 9c80ea7e-7544-496b-9f6f-764a4ae14373
		summarizeBy: none
		sourceColumn: Posted

		annotation SummarizationSetBy = Automatic

	column 'Avg offer'
		dataType: double
		lineageTag: b24ae3de-74c9-41e9-8355-fdf5c4b289c9
		summarizeBy: sum
		sourceColumn: Avg offer

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Duration(Days)
		dataType: int64
		formatString: 0
		lineageTag: 1c358264-4fe9-47b7-bd00-f848a439b247
		summarizeBy: sum
		sourceColumn: Duration(Days)

		annotation SummarizationSetBy = Automatic

	column 'Number of Offers'
		dataType: int64
		formatString: 0
		lineageTag: 543b2455-142f-4499-b0b7-578c3eba1b30
		summarizeBy: sum
		sourceColumn: Number of Offers

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Link
		dataType: string
		lineageTag: 993d1251-7f60-463c-b20a-e20f720c6803
		summarizeBy: none
		sourceColumn: Link

		annotation SummarizationSetBy = Automatic

	column Category_Arabic
		dataType: string
		lineageTag: 42a9525f-aeda-49ec-b6a1-cffda6bff0c3
		summarizeBy: none
		sourceColumn: Category_Arabic

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 98a415bf-7f86-4810-a177-3eb8bd2ac33a
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	partition Mostaql = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\Apps\GItHubRebo\Web_Scraping-\Data\Mostaqel.csv"),[Delimiter=",", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Renamed Columns" = Table.RenameColumns(#"Promoted Headers",{{"", "ID"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"ID", "Title", "Category_English", "Category_Arabic", "Posted", "Avg offer", "Duration(Days)", "Number of Offers", "Link", "_1", "_2"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns",{"_1", "_2"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"ID", Int64.Type}, {"Posted", type text}, {"Avg offer", type number}, {"Duration(Days)", Int64.Type}, {"Number of Offers", Int64.Type}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"Avg offer", type text}, {"Number of Offers", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

