table Table
	lineageTag: 162dcc84-6cc2-400e-b7f6-5e659a9128bd

	measure x = 1
		formatString: 0
		lineageTag: aa39152f-9ca2-40ac-a4c4-c3735130f5bd

	column Column
		formatString: 0
		lineageTag: eb968a9d-2c9c-48d9-87f0-94d0c097a9b0
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition Table = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 198c7f6a59924e3da48a1dd6c4277acc

