table UpWork_Skills
	lineageTag: 3c0945db-dad1-410f-b595-7d0fa3b5a065

	column index
		dataType: int64
		formatString: 0
		lineageTag: bf50227d-66bd-40cd-ad06-14adfadbcf08
		summarizeBy: sum
		sourceColumn: index

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		formatString: 0
		lineageTag: a9ef25a9-b073-4b0d-a091-1680a34181dc
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Tags
		dataType: string
		lineageTag: c2590ec0-5fb3-4238-ae50-97d225e8bffa
		summarizeBy: none
		sourceColumn: Tags

		annotation SummarizationSetBy = Automatic

	partition UpWork_Skills = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\Apps\GItHubRebo\Web_Scraping-\Upwork\jobs_expanded.csv"),[Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"index", Int64.Type}, {"ID", Int64.Type}, {"Tags", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

