table UpWork_Skills
	lineageTag: 3c0945db-dad1-410f-b595-7d0fa3b5a065

	column ID
		dataType: string
		lineageTag: a9ef25a9-b073-4b0d-a091-1680a34181dc
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Tags
		dataType: string
		lineageTag: c2590ec0-5fb3-4238-ae50-97d225e8bffa
		summarizeBy: none
		sourceColumn: Tags

		annotation SummarizationSetBy = Automatic

	column index
		dataType: string
		lineageTag: 24c823a4-1b8f-4d84-ab9c-fec73b571d09
		summarizeBy: none
		sourceColumn: index

		annotation SummarizationSetBy = Automatic

	partition UpWork_Skills = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\Apps\GItHubRebo\Web_Scraping-\Upwork\jobs_expanded.csv"),[Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
				in
				    #"Promoted Headers"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

