table UpWork_Skills
	lineageTag: 3c0945db-dad1-410f-b595-7d0fa3b5a065

	column Index
		dataType: string
		lineageTag: d85ee13b-0865-45a8-9d8a-5bbb927923e8
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: string
		lineageTag: a9ef25a9-b073-4b0d-a091-1680a34181dc
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Tags
		dataType: string
		lineageTag: c2590ec0-5fb3-4238-ae50-97d225e8bffa
		summarizeBy: none
		sourceColumn: Tags

		annotation SummarizationSetBy = Automatic

	partition UpWork_Skills = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\Apps\GItHubRebo\Web_Scraping-\Upwork\jobs_expanded.csv"),[Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Renamed Columns" = Table.RenameColumns(#"Promoted Headers",{{"", "Index"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

